// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/14/2026, 10:48:42 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/plugins/**/*.{js,ts,mjs}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/composables/**/*.{js,ts,mjs}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/utils/**/*.{js,ts,mjs}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/barter/barterborsa/barterborsa/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;