
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppHeader: typeof import("../components/app/AppHeader.vue")['default']
export const CommonAnnouncementBar: typeof import("../components/common/AnnouncementBar.vue")['default']
export const CommonCountdownTimer: typeof import("../components/common/CountdownTimer.vue")['default']
export const CommonEmptyState: typeof import("../components/common/EmptyState.vue")['default']
export const CommonFavoriteButton: typeof import("../components/common/FavoriteButton.vue")['default']
export const CommonLanguageSwitcher: typeof import("../components/common/LanguageSwitcher.vue")['default']
export const CommonSidebarWidget: typeof import("../components/common/SidebarWidget.vue")['default']
export const CommonToggleSwitch: typeof import("../components/common/ToggleSwitch.vue")['default']
export const HomeAuctions: typeof import("../components/home/HomeAuctions.vue")['default']
export const HomeBanner: typeof import("../components/home/HomeBanner.vue")['default']
export const HomeBarterPool: typeof import("../components/home/HomeBarterPool.vue")['default']
export const HomeBrands: typeof import("../components/home/HomeBrands.vue")['default']
export const HomeCampaigns: typeof import("../components/home/HomeCampaigns.vue")['default']
export const HomeCategories: typeof import("../components/home/HomeCategories.vue")['default']
export const HomeCategoryHighlights: typeof import("../components/home/HomeCategoryHighlights.vue")['default']
export const HomeFeaturedProducts: typeof import("../components/home/HomeFeaturedProducts.vue")['default']
export const HomeFlashSales: typeof import("../components/home/HomeFlashSales.vue")['default']
export const HomeGroupBuy: typeof import("../components/home/HomeGroupBuy.vue")['default']
export const HomeLotteries: typeof import("../components/home/HomeLotteries.vue")['default']
export const HomeNewsletter: typeof import("../components/home/HomeNewsletter.vue")['default']
export const HomePerformanceShowcase: typeof import("../components/home/HomePerformanceShowcase.vue")['default']
export const HomePersonalizedProducts: typeof import("../components/home/HomePersonalizedProducts.vue")['default']
export const HomeQuadCards: typeof import("../components/home/HomeQuadCards.vue")['default']
export const HomeQuickMenu: typeof import("../components/home/HomeQuickMenu.vue")['default']
export const HomeRestaurants: typeof import("../components/home/HomeRestaurants.vue")['default']
export const HomeSpecialOffers: typeof import("../components/home/HomeSpecialOffers.vue")['default']
export const HomeVendors: typeof import("../components/home/HomeVendors.vue")['default']
export const LayoutBazarXHero: typeof import("../components/layout/BazarXHero.vue")['default']
export const LayoutCategoryPillBar: typeof import("../components/layout/CategoryPillBar.vue")['default']
export const LayoutHomeBanner: typeof import("../components/layout/HomeBanner.vue")['default']
export const LayoutHomeCategoryGrid: typeof import("../components/layout/HomeCategoryGrid.vue")['default']
export const LayoutHorizontalProductScroll: typeof import("../components/layout/HorizontalProductScroll.vue")['default']
export const LayoutMegaMenu: typeof import("../components/layout/MegaMenu.vue")['default']
export const LayoutMiddleBanner: typeof import("../components/layout/MiddleBanner.vue")['default']
export const LayoutPersonalizedFeed: typeof import("../components/layout/PersonalizedFeed.vue")['default']
export const LayoutPremiumSideAd: typeof import("../components/layout/PremiumSideAd.vue")['default']
export const LayoutQuadCard: typeof import("../components/layout/QuadCard.vue")['default']
export const LayoutStickyCartBar: typeof import("../components/layout/StickyCartBar.vue")['default']
export const ProductAdvancedSearch: typeof import("../components/product/AdvancedSearch.vue")['default']
export const ProductCategoryDiscoverBar: typeof import("../components/product/CategoryDiscoverBar.vue")['default']
export const ProductOtherSellers: typeof import("../components/product/OtherSellers.vue")['default']
export const ProductBreadcrumb: typeof import("../components/product/ProductBreadcrumb.vue")['default']
export const ProductCard: typeof import("../components/product/ProductCard.vue")['default']
export const ProductCardSkeleton: typeof import("../components/product/ProductCardSkeleton.vue")['default']
export const ProductFilters: typeof import("../components/product/ProductFilters.vue")['default']
export const ProductGallery: typeof import("../components/product/ProductGallery.vue")['default']
export const ProductGrid: typeof import("../components/product/ProductGrid.vue")['default']
export const ProductImage: typeof import("../components/product/ProductImage.vue")['default']
export const ProductInfo: typeof import("../components/product/ProductInfo.vue")['default']
export const ProductItem: typeof import("../components/product/ProductItem.vue")['default']
export const ProductSort: typeof import("../components/product/ProductSort.vue")['default']
export const ProductSurplusFilters: typeof import("../components/product/SurplusFilters.vue")['default']
export const ProductDetailProductDeliveryEstimation: typeof import("../components/product/detail/ProductDeliveryEstimation.vue")['default']
export const ProductDetailProductDescription: typeof import("../components/product/detail/ProductDescription.vue")['default']
export const ProductDetailProductGallery: typeof import("../components/product/detail/ProductGallery.vue")['default']
export const ProductDetailProductMainInfo: typeof import("../components/product/detail/ProductMainInfo.vue")['default']
export const ProductDetailProductPurchaseActions: typeof import("../components/product/detail/ProductPurchaseActions.vue")['default']
export const ProductDetailProductReviewForm: typeof import("../components/product/detail/ProductReviewForm.vue")['default']
export const ProductDetailProductReviewItem: typeof import("../components/product/detail/ProductReviewItem.vue")['default']
export const ProductDetailProductReviews: typeof import("../components/product/detail/ProductReviews.vue")['default']
export const ProductDetailProductSidebar: typeof import("../components/product/detail/ProductSidebar.vue")['default']
export const ProductDetailProductSpecifications: typeof import("../components/product/detail/ProductSpecifications.vue")['default']
export const ProductDetailProductTabs: typeof import("../components/product/detail/ProductTabs.vue")['default']
export const ProductFormAttributes: typeof import("../components/product/form/ProductFormAttributes.vue")['default']
export const ProductFormBasics: typeof import("../components/product/form/ProductFormBasics.vue")['default']
export const ProductFormContent: typeof import("../components/product/form/ProductFormContent.vue")['default']
export const ProductFormEcosystem: typeof import("../components/product/form/ProductFormEcosystem.vue")['default']
export const ProductFormIdentity: typeof import("../components/product/form/ProductFormIdentity.vue")['default']
export const ProductFormInventory: typeof import("../components/product/form/ProductFormInventory.vue")['default']
export const ProductFormLogistics: typeof import("../components/product/form/ProductFormLogistics.vue")['default']
export const ProductFormMarketing: typeof import("../components/product/form/ProductFormMarketing.vue")['default']
export const ProductFormMedia: typeof import("../components/product/form/ProductFormMedia.vue")['default']
export const ProductFormNavigation: typeof import("../components/product/form/ProductFormNavigation.vue")['default']
export const SearchBar: typeof import("../components/search/SearchBar.vue")['default']
export const UiButton: typeof import("../components/ui/UiButton.vue")['default']
export const UiPagination: typeof import("../components/ui/UiPagination.vue")['default']
export const UiSlideOver: typeof import("../components/ui/UiSlideOver.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@8.5.6_magicast@0.5.2_rollup@4.60.1_vue@3.5.32_typescript@5.9.3_/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@8.5.6_magicast@0.5.2_rollup@4.60.1_vue@3.5.32_typescript@5.9.3_/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const Icon: typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_magicast@0.5.2_vite@7.3.2_@types+node@20.19.39_jiti@2.6.1_terser@5.46.1_yaml_fe5xqkdijfgjycpbay6be73esm/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_magicast@0.5.2_vite@7.3.2_@types+node@20.19.39_jiti@2.6.1_terser@5.46.1_yaml_fe5xqkdijfgjycpbay6be73esm/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppHeader: LazyComponent<typeof import("../components/app/AppHeader.vue")['default']>
export const LazyCommonAnnouncementBar: LazyComponent<typeof import("../components/common/AnnouncementBar.vue")['default']>
export const LazyCommonCountdownTimer: LazyComponent<typeof import("../components/common/CountdownTimer.vue")['default']>
export const LazyCommonEmptyState: LazyComponent<typeof import("../components/common/EmptyState.vue")['default']>
export const LazyCommonFavoriteButton: LazyComponent<typeof import("../components/common/FavoriteButton.vue")['default']>
export const LazyCommonLanguageSwitcher: LazyComponent<typeof import("../components/common/LanguageSwitcher.vue")['default']>
export const LazyCommonSidebarWidget: LazyComponent<typeof import("../components/common/SidebarWidget.vue")['default']>
export const LazyCommonToggleSwitch: LazyComponent<typeof import("../components/common/ToggleSwitch.vue")['default']>
export const LazyHomeAuctions: LazyComponent<typeof import("../components/home/HomeAuctions.vue")['default']>
export const LazyHomeBanner: LazyComponent<typeof import("../components/home/HomeBanner.vue")['default']>
export const LazyHomeBarterPool: LazyComponent<typeof import("../components/home/HomeBarterPool.vue")['default']>
export const LazyHomeBrands: LazyComponent<typeof import("../components/home/HomeBrands.vue")['default']>
export const LazyHomeCampaigns: LazyComponent<typeof import("../components/home/HomeCampaigns.vue")['default']>
export const LazyHomeCategories: LazyComponent<typeof import("../components/home/HomeCategories.vue")['default']>
export const LazyHomeCategoryHighlights: LazyComponent<typeof import("../components/home/HomeCategoryHighlights.vue")['default']>
export const LazyHomeFeaturedProducts: LazyComponent<typeof import("../components/home/HomeFeaturedProducts.vue")['default']>
export const LazyHomeFlashSales: LazyComponent<typeof import("../components/home/HomeFlashSales.vue")['default']>
export const LazyHomeGroupBuy: LazyComponent<typeof import("../components/home/HomeGroupBuy.vue")['default']>
export const LazyHomeLotteries: LazyComponent<typeof import("../components/home/HomeLotteries.vue")['default']>
export const LazyHomeNewsletter: LazyComponent<typeof import("../components/home/HomeNewsletter.vue")['default']>
export const LazyHomePerformanceShowcase: LazyComponent<typeof import("../components/home/HomePerformanceShowcase.vue")['default']>
export const LazyHomePersonalizedProducts: LazyComponent<typeof import("../components/home/HomePersonalizedProducts.vue")['default']>
export const LazyHomeQuadCards: LazyComponent<typeof import("../components/home/HomeQuadCards.vue")['default']>
export const LazyHomeQuickMenu: LazyComponent<typeof import("../components/home/HomeQuickMenu.vue")['default']>
export const LazyHomeRestaurants: LazyComponent<typeof import("../components/home/HomeRestaurants.vue")['default']>
export const LazyHomeSpecialOffers: LazyComponent<typeof import("../components/home/HomeSpecialOffers.vue")['default']>
export const LazyHomeVendors: LazyComponent<typeof import("../components/home/HomeVendors.vue")['default']>
export const LazyLayoutBazarXHero: LazyComponent<typeof import("../components/layout/BazarXHero.vue")['default']>
export const LazyLayoutCategoryPillBar: LazyComponent<typeof import("../components/layout/CategoryPillBar.vue")['default']>
export const LazyLayoutHomeBanner: LazyComponent<typeof import("../components/layout/HomeBanner.vue")['default']>
export const LazyLayoutHomeCategoryGrid: LazyComponent<typeof import("../components/layout/HomeCategoryGrid.vue")['default']>
export const LazyLayoutHorizontalProductScroll: LazyComponent<typeof import("../components/layout/HorizontalProductScroll.vue")['default']>
export const LazyLayoutMegaMenu: LazyComponent<typeof import("../components/layout/MegaMenu.vue")['default']>
export const LazyLayoutMiddleBanner: LazyComponent<typeof import("../components/layout/MiddleBanner.vue")['default']>
export const LazyLayoutPersonalizedFeed: LazyComponent<typeof import("../components/layout/PersonalizedFeed.vue")['default']>
export const LazyLayoutPremiumSideAd: LazyComponent<typeof import("../components/layout/PremiumSideAd.vue")['default']>
export const LazyLayoutQuadCard: LazyComponent<typeof import("../components/layout/QuadCard.vue")['default']>
export const LazyLayoutStickyCartBar: LazyComponent<typeof import("../components/layout/StickyCartBar.vue")['default']>
export const LazyProductAdvancedSearch: LazyComponent<typeof import("../components/product/AdvancedSearch.vue")['default']>
export const LazyProductCategoryDiscoverBar: LazyComponent<typeof import("../components/product/CategoryDiscoverBar.vue")['default']>
export const LazyProductOtherSellers: LazyComponent<typeof import("../components/product/OtherSellers.vue")['default']>
export const LazyProductBreadcrumb: LazyComponent<typeof import("../components/product/ProductBreadcrumb.vue")['default']>
export const LazyProductCard: LazyComponent<typeof import("../components/product/ProductCard.vue")['default']>
export const LazyProductCardSkeleton: LazyComponent<typeof import("../components/product/ProductCardSkeleton.vue")['default']>
export const LazyProductFilters: LazyComponent<typeof import("../components/product/ProductFilters.vue")['default']>
export const LazyProductGallery: LazyComponent<typeof import("../components/product/ProductGallery.vue")['default']>
export const LazyProductGrid: LazyComponent<typeof import("../components/product/ProductGrid.vue")['default']>
export const LazyProductImage: LazyComponent<typeof import("../components/product/ProductImage.vue")['default']>
export const LazyProductInfo: LazyComponent<typeof import("../components/product/ProductInfo.vue")['default']>
export const LazyProductItem: LazyComponent<typeof import("../components/product/ProductItem.vue")['default']>
export const LazyProductSort: LazyComponent<typeof import("../components/product/ProductSort.vue")['default']>
export const LazyProductSurplusFilters: LazyComponent<typeof import("../components/product/SurplusFilters.vue")['default']>
export const LazyProductDetailProductDeliveryEstimation: LazyComponent<typeof import("../components/product/detail/ProductDeliveryEstimation.vue")['default']>
export const LazyProductDetailProductDescription: LazyComponent<typeof import("../components/product/detail/ProductDescription.vue")['default']>
export const LazyProductDetailProductGallery: LazyComponent<typeof import("../components/product/detail/ProductGallery.vue")['default']>
export const LazyProductDetailProductMainInfo: LazyComponent<typeof import("../components/product/detail/ProductMainInfo.vue")['default']>
export const LazyProductDetailProductPurchaseActions: LazyComponent<typeof import("../components/product/detail/ProductPurchaseActions.vue")['default']>
export const LazyProductDetailProductReviewForm: LazyComponent<typeof import("../components/product/detail/ProductReviewForm.vue")['default']>
export const LazyProductDetailProductReviewItem: LazyComponent<typeof import("../components/product/detail/ProductReviewItem.vue")['default']>
export const LazyProductDetailProductReviews: LazyComponent<typeof import("../components/product/detail/ProductReviews.vue")['default']>
export const LazyProductDetailProductSidebar: LazyComponent<typeof import("../components/product/detail/ProductSidebar.vue")['default']>
export const LazyProductDetailProductSpecifications: LazyComponent<typeof import("../components/product/detail/ProductSpecifications.vue")['default']>
export const LazyProductDetailProductTabs: LazyComponent<typeof import("../components/product/detail/ProductTabs.vue")['default']>
export const LazyProductFormAttributes: LazyComponent<typeof import("../components/product/form/ProductFormAttributes.vue")['default']>
export const LazyProductFormBasics: LazyComponent<typeof import("../components/product/form/ProductFormBasics.vue")['default']>
export const LazyProductFormContent: LazyComponent<typeof import("../components/product/form/ProductFormContent.vue")['default']>
export const LazyProductFormEcosystem: LazyComponent<typeof import("../components/product/form/ProductFormEcosystem.vue")['default']>
export const LazyProductFormIdentity: LazyComponent<typeof import("../components/product/form/ProductFormIdentity.vue")['default']>
export const LazyProductFormInventory: LazyComponent<typeof import("../components/product/form/ProductFormInventory.vue")['default']>
export const LazyProductFormLogistics: LazyComponent<typeof import("../components/product/form/ProductFormLogistics.vue")['default']>
export const LazyProductFormMarketing: LazyComponent<typeof import("../components/product/form/ProductFormMarketing.vue")['default']>
export const LazyProductFormMedia: LazyComponent<typeof import("../components/product/form/ProductFormMedia.vue")['default']>
export const LazyProductFormNavigation: LazyComponent<typeof import("../components/product/form/ProductFormNavigation.vue")['default']>
export const LazySearchBar: LazyComponent<typeof import("../components/search/SearchBar.vue")['default']>
export const LazyUiButton: LazyComponent<typeof import("../components/ui/UiButton.vue")['default']>
export const LazyUiPagination: LazyComponent<typeof import("../components/ui/UiPagination.vue")['default']>
export const LazyUiSlideOver: LazyComponent<typeof import("../components/ui/UiSlideOver.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@8.5.6_magicast@0.5.2_rollup@4.60.1_vue@3.5.32_typescript@5.9.3_/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@8.5.6_magicast@0.5.2_rollup@4.60.1_vue@3.5.32_typescript@5.9.3_/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyIcon: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_magicast@0.5.2_vite@7.3.2_@types+node@20.19.39_jiti@2.6.1_terser@5.46.1_yaml_fe5xqkdijfgjycpbay6be73esm/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']>
export const LazyIconCSS: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt-icon@0.6.10_magicast@0.5.2_vite@7.3.2_@types+node@20.19.39_jiti@2.6.1_terser@5.46.1_yaml_fe5xqkdijfgjycpbay6be73esm/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.21.2_@emnapi+core@1.9.2_@emnapi+runtime@1.9.2_@parcel+watcher@2.5.6_@types+node@20.19._vprfopv77pl74cvuztsqqrmssq/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
