// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/15/2026, 7:07:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/macbook/Desktop/bazarx/apps/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/plugins/**/*.{js,ts,mjs}","/Users/macbook/Desktop/bazarx/apps/frontend/composables/**/*.{js,ts,mjs}","/Users/macbook/Desktop/bazarx/apps/frontend/utils/**/*.{js,ts,mjs}","/Users/macbook/Desktop/bazarx/apps/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbook/Desktop/bazarx/apps/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;