// apps/backend/src/modules/analytics/domain/enums/analytics.enums.ts

export enum AnalyticsEventType {
  PAGE_VIEW = 'PAGE_VIEW',
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  SEARCH = 'SEARCH',
  ADD_TO_CART = 'ADD_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  PURCHASE = 'PURCHASE',
  BARTER_VIEW = 'BARTER_VIEW',
  BARTER_OFFER = 'BARTER_OFFER',
  AD_CLICK = 'AD_CLICK',
  AD_IMPRESSION = 'AD_IMPRESSION',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  CHECKOUT_START = 'CHECKOUT_START',
  CHECKOUT_COMPLETE = 'CHECKOUT_COMPLETE'
}

export enum ActivityType {
  VIEW = 'VIEW',
  CLICK = 'CLICK',
  CART_ADD = 'CART_ADD',
  PURCHASE = 'PURCHASE',
  WISHLIST = 'WISHLIST'
}
